### ISSUE TITLE
Issues using these styles on Python 3.6

### ISSUE THREAD

**Issue by jmichalicek** [meganlkm/pygments-solarized#2]
When trying to use these styles in Python 3.6 I ran into issues importing the actual styles when running pygmentize.  I've made a PR #1  using `absolute_import` to work with python 2 and 3

**Comment by meganlkm** [comment]
[version 0.0.3](https://github.com/meganlkm/pygments-solarized/releases/tag/0.0.3) uploaded to pypi.
